### ISSUE TITLE
Unable to sign using trust wallet browser

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot.js#972]
If you try to vote on snapshot.org on trust wallet's browser, you will see it fails silently

![image](https://github.com/snapshot-labs/snapshot.js/assets/15967809/86b08300-1107-4017-ab17-270f80989f29)

After some debugging, I got to know the error `provided chainid does not match currently active chain`
and i found that we are not passing `chainId` here https://github.com/snapshot-labs/snapshot.js/blob/master/src/sign/index.ts#L49 

and if we pass it, it works fine ✅ But may cause problems with other wallets or wallets using other chains
```[tasklist]
### Tasks
- [ ] Add chainId and try on metamask
- [ ] Add chanid and try on metamask using different chain
- [ ] Try on trust wallet with different chains
- [ ] Try on wallet connect with different chains
```
