### ISSUE TITLE
Enable delegation on sepolia 

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot.js#978]
```[tasklist]
### Tasks
- [x] Deploy delegation contract (https://sepolia.etherscan.io/address/0x469788fE6E9E9681C6ebF3bF78e7Fd26Fc015446#code)
- [x] Deploy delegation subgraph https://github.com/snapshot-labs/snapshot-subgraph/pull/15
- [x] Update snapshot.js to use new subgraph https://github.com/snapshot-labs/snapshot.js/pull/979
```

**Comment by tknoch-symphony** [comment]
@ChaituVR I see the graphQL endpoint is active and it is possible to delegate on snapshot UI but it is throwing an error when fetching the delegates and current delegate

<img width="716" alt="image" src="https://github.com/snapshot-labs/snapshot.js/assets/84320816/f9675d68-c929-4767-8df2-6f4b2ee415c3">

**Comment by ChaituVR** [comment]
Could you plz share the link for this @tknoch-symphony

**Comment by tknoch-symphony** [comment]
@ChaituVR https://testnet.snapshot.org/#/delegate/karate-combat-dev.eth
